services:
  - type: web
    name: recharge-backend
    env: node
    buildCommand: cd backend && npm install
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGO_URI
        value: mongodb+srv://swetha:sswetha123@mernproject.fwp2kyj.mongodb.net/?appName=mernproject
      - key: JWT_SECRET
        value: a8f5f167f44f4964e6c998dee827110c
      - key: PORT
        value: 10000

  - type: web
    name: recharge-frontend
    env: static
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: ./frontend/build
    envVars:
      - key: REACT_APP_API_URL
        value: https://recharge-backend.onrender.com