services:
  - type: web
    name: mernproject1-backend
    env: node
    rootDir: backend
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGO_URI
        value: mongodb+srv://swetha:swetha123@mernproject.fwp2kyj.mongodb.net/?appName=mernproject
      - key: JWT_SECRET
        value: a8f5f167f44f4964e6c998dee827110c

  - type: web
    name: mernproject1-frontend
    env: node
    rootDir: frontend
    buildCommand: npm install && npm run build
    startCommand: npx serve -s build -l 3000
    envVars:
      - key: REACT_APP_API_URL
        value: https://mernproject1-backend.onrender.com